name: Deploy Laravel to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H fkstudio.my.id >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_ed25519 webserver@fkstudio.my.id "\
            whoami && \
            cd /var/www/fkstudio && \
            git pull origin main && \
            composer install --no-interaction --prefer-dist --optimize-autoloader && \
            php artisan migrate --force && \
            php artisan optimize:clear && \
          "
