name: Deploy Laravel to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ssh.fkstudio.my.id >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -o BatchMode=yes -o StrictHostKeyChecking=no webserver@ssh.fkstudio.my.id whoami

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o BatchMode=yes webserver@fkstudio.my.id << 'EOF'
            set -e  # Exit immediately if any command fails
            cd /var/www/fkstudio
            echo "Current directory: $(pwd)"
            echo "Pulling latest changes from main branch..."
            git fetch origin main
            git reset --hard origin/main
            echo "Running composer install..."
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            echo "Running migrations..."
            php artisan migrate --force
            echo "Clearing cache..."
            php artisan optimize:clear
            echo "Deployment completed successfully!"
          EOF