name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ssh.fkstudio.my.id >> ~/.ssh/known_hosts

      - name: Test SSH
        run: |
          ssh -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              webserver@ssh.fkstudio.my.id whoami

      - name: Deploy Laravel
        run: |
          ssh -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              webserver@ssh.fkstudio.my.id << 'EOF'
                set -e
                whoami
                cd /var/www/fkstudio
                git fetch origin main
                git reset --hard origin/main
                composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
                php artisan migrate --force
                php artisan optimize:clear
          EOF
