name: Deploy Laravel to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb

      - name: Test SSH via Cloudflare
        run: |
          ssh -o ProxyCommand="cloudflared access ssh --hostname %h" \
              -i ~/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=no \
              webserver@ssh.fkstudio.my.id whoami


      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ssh.fkstudio.my.id >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -o BatchMode=yes -o StrictHostKeyChecking=no webserver@ssh.fkstudio.my.id whoami

      - name: Deploy to Server
        run: |
          ssh -o ProxyCommand="cloudflared access ssh --hostname %h" \
              -i ~/.ssh/id_ed25519 webserver@ssh.fkstudio.my.id << 'EOF'
              cd /var/www/fkstudio
              git fetch origin main
              git reset --hard origin/main
              composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
              php artisan migrate --force
              php artisan optimize:clear
          EOF
