name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # SSH config pakai cloudflared proxy
          cat > ~/.ssh/config <<EOL
          Host fkstudio-vm
              HostName ssh.fkstudio.my.id
              User webserver
              IdentityFile ~/.ssh/id_rsa
              ProxyCommand cloudflared access ssh --hostname %h
              ServerAliveInterval 30
              IdentitiesOnly yes
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
          EOL

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          sudo mv cloudflared /usr/local/bin/
          sudo chmod +x /usr/local/bin/cloudflared

      - name: Deploy to Server
        run: |
          ssh fkstudio-vm "git config --global --add safe.directory /var/www/fkstudio && cd /var/www/fkstudio && \
            git fetch origin main && \
            git pull origin main && \
            composer install --no-interaction --prefer-dist --optimize-autoloader && \
            php artisan migrate --force && \
            php artisan optimize:clear && \
            npm install
          "
